#!/bin/bash
set -e

cat <<EOSQL > /tmp/init.sql
  CREATE USER $WORKSPACES_DB_USER with encrypted password '$WORKSPACES_DB_PASS';
  CREATE DATABASE $WORKSPACES_DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE $WORKSPACES_DB_USER TO $WORKSPACES_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" < /tmp/init.sql
